// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type CounterDenyInfo struct {
	LastNs uint64
	Count  uint32
	Reason uint32
}

type CounterFlowEvent struct {
	TimestampNs  uint64
	SrcIp        uint32
	DstIp        uint32
	SrcPort      uint16
	DstPort      uint16
	Proto        uint8
	Verdict      uint8
	Pad0         uint16
	SrcIdentity  uint32
	DstIdentity  uint32
	Bytes        uint32
	Pad1         uint32
	LatencyNs    uint64
	L7StatusCode uint16
	Pad2         [3]uint16
}

type CounterFlowKey struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type CounterMeridianSchemaVersion uint32

const (
	CounterMeridianSchemaVersionMERIDIAN_SCHEMA_VERSION CounterMeridianSchemaVersion = 2
)

type CounterPolicyKey struct {
	SrcId     uint32
	DstId     uint32
	DstPort   uint16
	Proto     uint8
	Direction uint8
}

type CounterPolicyVerdict struct {
	Action uint8
	Flags  uint8
	Pad    uint16
}

// LoadCounter returns the embedded CollectionSpec for Counter.
func LoadCounter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CounterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Counter: %w", err)
	}

	return spec, err
}

// LoadCounterObjects loads Counter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CounterObjects
//	*CounterPrograms
//	*CounterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCounterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCounter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CounterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CounterSpecs struct {
	CounterProgramSpecs
	CounterMapSpecs
	CounterVariableSpecs
}

// CounterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CounterProgramSpecs struct {
	MeridianCounter *ebpf.ProgramSpec `ebpf:"meridian_counter"`
}

// CounterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CounterMapSpecs struct {
	DeniedFlowsMap    *ebpf.MapSpec `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.MapSpec `ebpf:"flow_events"`
	IdentityMap       *ebpf.MapSpec `ebpf:"identity_map"`
	MetricsMap        *ebpf.MapSpec `ebpf:"metrics_map"`
	PolicyMap         *ebpf.MapSpec `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.MapSpec `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.MapSpec `ebpf:"schema_sentinel_map"`
}

// CounterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CounterVariableSpecs struct {
}

// CounterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCounterObjects or ebpf.CollectionSpec.LoadAndAssign.
type CounterObjects struct {
	CounterPrograms
	CounterMaps
	CounterVariables
}

func (o *CounterObjects) Close() error {
	return _CounterClose(
		&o.CounterPrograms,
		&o.CounterMaps,
	)
}

// CounterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCounterObjects or ebpf.CollectionSpec.LoadAndAssign.
type CounterMaps struct {
	DeniedFlowsMap    *ebpf.Map `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.Map `ebpf:"flow_events"`
	IdentityMap       *ebpf.Map `ebpf:"identity_map"`
	MetricsMap        *ebpf.Map `ebpf:"metrics_map"`
	PolicyMap         *ebpf.Map `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.Map `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.Map `ebpf:"schema_sentinel_map"`
}

func (m *CounterMaps) Close() error {
	return _CounterClose(
		m.DeniedFlowsMap,
		m.FlowEvents,
		m.IdentityMap,
		m.MetricsMap,
		m.PolicyMap,
		m.RuntimeConfigMap,
		m.SchemaSentinelMap,
	)
}

// CounterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCounterObjects or ebpf.CollectionSpec.LoadAndAssign.
type CounterVariables struct {
}

// CounterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCounterObjects or ebpf.CollectionSpec.LoadAndAssign.
type CounterPrograms struct {
	MeridianCounter *ebpf.Program `ebpf:"meridian_counter"`
}

func (p *CounterPrograms) Close() error {
	return _CounterClose(
		p.MeridianCounter,
	)
}

func _CounterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed counter_bpfel.o
var _CounterBytes []byte
