// Package bpf hosts the eBPF C sources and their bpf2go-generated Go bindings.
//
// Each kernel program is a single .c file compiled to one CO-RE object with a
// matching type-safe Go loader, generated by cilium/ebpf's bpf2go. The
// generated files (<name>_bpfel.go + <name>_bpfel.o) are COMMITTED; we never
// hand-write Go mirrors of cross-boundary structs (CC-6).
//
// Run codegen via `make ebpf` (Linux only) — the Makefile exports CLANG,
// STRIP, BPF_TARGET, and BPF_CFLAGS, which `go generate` substitutes into the
// directives below. Running `go generate ./bpf/...` without those variables
// set will fail; that is intentional: the Makefile is the supported entry
// point so the pinned toolchain is always used (determinism gate `make
// verify-gen`).
//
// Adding a new program (e.g. Phase 1's tc_ingress.c) is exactly one new
// //go:generate line following the same pattern; list every cross-boundary
// struct with -type so its Go mirror is generated, never hand-written.
package bpf

// Phase 0 program + the FULL v2 cross-boundary type set (MER-14 contract
// freeze). counter.c includes meridian_maps.h, so every shared map — and
// therefore every cross-boundary struct plus the schema-version enum (the
// sentinel map's value type) — is in this object's BTF; listing them here
// makes bpf2go generate the canonical Go mirrors.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target $BPF_TARGET -go-package bpf -output-dir . -cc $CLANG -strip $STRIP -cflags "$BPF_CFLAGS" -type flow_event -type policy_key -type policy_verdict -type flow_key -type deny_info -type meridian_schema_version Counter counter.c

// Phase 1 — production tc_ingress parser + identity resolution.
//
// Prefix convention (MER-13/MER-14): bpf2go prefixes generated TYPE names
// with the object name, so cross-boundary types are generated ONCE, under
// the Counter prefix above (CounterPolicyKey, ...). Do NOT re-list -type
// here — that would mint a parallel TcIngress* mirror set. Go code uses the
// Counter-prefixed mirrors until a combined object lands.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target $BPF_TARGET -go-package bpf -output-dir . -cc $CLANG -strip $STRIP -cflags "$BPF_CFLAGS" TcIngress tc_ingress.c
