// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type SkMsgDenyInfo struct {
	LastNs uint64
	Count  uint32
	Reason uint32
}

type SkMsgFlowEvent struct {
	TimestampNs  uint64
	SrcIp        uint32
	DstIp        uint32
	SrcPort      uint16
	DstPort      uint16
	Proto        uint8
	Verdict      uint8
	Pad0         uint16
	SrcIdentity  uint32
	DstIdentity  uint32
	Bytes        uint32
	Pad1         uint32
	LatencyNs    uint64
	L7StatusCode uint16
	Pad2         [3]uint16
}

type SkMsgFlowKey struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type SkMsgMeridianSchemaVersion uint32

const (
	SkMsgMeridianSchemaVersionMERIDIAN_SCHEMA_VERSION SkMsgMeridianSchemaVersion = 2
)

type SkMsgPolicyKey struct {
	SrcId     uint32
	DstId     uint32
	DstPort   uint16
	Proto     uint8
	Direction uint8
}

type SkMsgPolicyVerdict struct {
	Action uint8
	Flags  uint8
	Pad    uint16
}

type SkMsgSockKey struct {
	DstIp   uint32
	DstPort uint16
	Pad     uint16
}

// LoadSkMsg returns the embedded CollectionSpec for SkMsg.
func LoadSkMsg() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SkMsgBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SkMsg: %w", err)
	}

	return spec, err
}

// LoadSkMsgObjects loads SkMsg and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SkMsgObjects
//	*SkMsgPrograms
//	*SkMsgMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSkMsgObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSkMsg()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SkMsgSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SkMsgSpecs struct {
	SkMsgProgramSpecs
	SkMsgMapSpecs
	SkMsgVariableSpecs
}

// SkMsgProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SkMsgProgramSpecs struct {
	MeridianSkMsg *ebpf.ProgramSpec `ebpf:"meridian_sk_msg"`
}

// SkMsgMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SkMsgMapSpecs struct {
	DeniedFlowsMap    *ebpf.MapSpec `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.MapSpec `ebpf:"flow_events"`
	IdentityMap       *ebpf.MapSpec `ebpf:"identity_map"`
	MetricsMap        *ebpf.MapSpec `ebpf:"metrics_map"`
	PolicyMap         *ebpf.MapSpec `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.MapSpec `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.MapSpec `ebpf:"schema_sentinel_map"`
	Sockhash          *ebpf.MapSpec `ebpf:"sockhash"`
}

// SkMsgVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SkMsgVariableSpecs struct {
}

// SkMsgObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSkMsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type SkMsgObjects struct {
	SkMsgPrograms
	SkMsgMaps
	SkMsgVariables
}

func (o *SkMsgObjects) Close() error {
	return _SkMsgClose(
		&o.SkMsgPrograms,
		&o.SkMsgMaps,
	)
}

// SkMsgMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSkMsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type SkMsgMaps struct {
	DeniedFlowsMap    *ebpf.Map `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.Map `ebpf:"flow_events"`
	IdentityMap       *ebpf.Map `ebpf:"identity_map"`
	MetricsMap        *ebpf.Map `ebpf:"metrics_map"`
	PolicyMap         *ebpf.Map `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.Map `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.Map `ebpf:"schema_sentinel_map"`
	Sockhash          *ebpf.Map `ebpf:"sockhash"`
}

func (m *SkMsgMaps) Close() error {
	return _SkMsgClose(
		m.DeniedFlowsMap,
		m.FlowEvents,
		m.IdentityMap,
		m.MetricsMap,
		m.PolicyMap,
		m.RuntimeConfigMap,
		m.SchemaSentinelMap,
		m.Sockhash,
	)
}

// SkMsgVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSkMsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type SkMsgVariables struct {
}

// SkMsgPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSkMsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type SkMsgPrograms struct {
	MeridianSkMsg *ebpf.Program `ebpf:"meridian_sk_msg"`
}

func (p *SkMsgPrograms) Close() error {
	return _SkMsgClose(
		p.MeridianSkMsg,
	)
}

func _SkMsgClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed skmsg_bpfel.o
var _SkMsgBytes []byte
