// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type SockOpsDenyInfo struct {
	LastNs uint64
	Count  uint32
	Reason uint32
}

type SockOpsFlowEvent struct {
	TimestampNs  uint64
	SrcIp        uint32
	DstIp        uint32
	SrcPort      uint16
	DstPort      uint16
	Proto        uint8
	Verdict      uint8
	Pad0         uint16
	SrcIdentity  uint32
	DstIdentity  uint32
	Bytes        uint32
	Pad1         uint32
	LatencyNs    uint64
	L7StatusCode uint16
	Pad2         [3]uint16
}

type SockOpsFlowKey struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type SockOpsMeridianSchemaVersion uint32

const (
	SockOpsMeridianSchemaVersionMERIDIAN_SCHEMA_VERSION SockOpsMeridianSchemaVersion = 2
)

type SockOpsPolicyKey struct {
	SrcId     uint32
	DstId     uint32
	DstPort   uint16
	Proto     uint8
	Direction uint8
}

type SockOpsPolicyVerdict struct {
	Action uint8
	Flags  uint8
	Pad    uint16
}

type SockOpsSockKey struct {
	DstIp   uint32
	DstPort uint16
	Pad     uint16
}

// LoadSockOps returns the embedded CollectionSpec for SockOps.
func LoadSockOps() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockOpsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SockOps: %w", err)
	}

	return spec, err
}

// LoadSockOpsObjects loads SockOps and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SockOpsObjects
//	*SockOpsPrograms
//	*SockOpsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSockOpsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSockOps()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SockOpsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockOpsSpecs struct {
	SockOpsProgramSpecs
	SockOpsMapSpecs
	SockOpsVariableSpecs
}

// SockOpsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockOpsProgramSpecs struct {
	MeridianSockOps *ebpf.ProgramSpec `ebpf:"meridian_sock_ops"`
}

// SockOpsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockOpsMapSpecs struct {
	DeniedFlowsMap    *ebpf.MapSpec `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.MapSpec `ebpf:"flow_events"`
	IdentityMap       *ebpf.MapSpec `ebpf:"identity_map"`
	MetricsMap        *ebpf.MapSpec `ebpf:"metrics_map"`
	PolicyMap         *ebpf.MapSpec `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.MapSpec `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.MapSpec `ebpf:"schema_sentinel_map"`
	Sockhash          *ebpf.MapSpec `ebpf:"sockhash"`
}

// SockOpsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SockOpsVariableSpecs struct {
}

// SockOpsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSockOpsObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockOpsObjects struct {
	SockOpsPrograms
	SockOpsMaps
	SockOpsVariables
}

func (o *SockOpsObjects) Close() error {
	return _SockOpsClose(
		&o.SockOpsPrograms,
		&o.SockOpsMaps,
	)
}

// SockOpsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSockOpsObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockOpsMaps struct {
	DeniedFlowsMap    *ebpf.Map `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.Map `ebpf:"flow_events"`
	IdentityMap       *ebpf.Map `ebpf:"identity_map"`
	MetricsMap        *ebpf.Map `ebpf:"metrics_map"`
	PolicyMap         *ebpf.Map `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.Map `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.Map `ebpf:"schema_sentinel_map"`
	Sockhash          *ebpf.Map `ebpf:"sockhash"`
}

func (m *SockOpsMaps) Close() error {
	return _SockOpsClose(
		m.DeniedFlowsMap,
		m.FlowEvents,
		m.IdentityMap,
		m.MetricsMap,
		m.PolicyMap,
		m.RuntimeConfigMap,
		m.SchemaSentinelMap,
		m.Sockhash,
	)
}

// SockOpsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSockOpsObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockOpsVariables struct {
}

// SockOpsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSockOpsObjects or ebpf.CollectionSpec.LoadAndAssign.
type SockOpsPrograms struct {
	MeridianSockOps *ebpf.Program `ebpf:"meridian_sock_ops"`
}

func (p *SockOpsPrograms) Close() error {
	return _SockOpsClose(
		p.MeridianSockOps,
	)
}

func _SockOpsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockops_bpfel.o
var _SockOpsBytes []byte
