// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type TcEgressDenyInfo struct {
	LastNs uint64
	Count  uint32
	Reason uint32
}

type TcEgressFlowEvent struct {
	TimestampNs  uint64
	SrcIp        uint32
	DstIp        uint32
	SrcPort      uint16
	DstPort      uint16
	Proto        uint8
	Verdict      uint8
	Pad0         uint16
	SrcIdentity  uint32
	DstIdentity  uint32
	Bytes        uint32
	Pad1         uint32
	LatencyNs    uint64
	L7StatusCode uint16
	Pad2         [3]uint16
}

type TcEgressFlowKey struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type TcEgressMeridianSchemaVersion uint32

const (
	TcEgressMeridianSchemaVersionMERIDIAN_SCHEMA_VERSION TcEgressMeridianSchemaVersion = 2
)

type TcEgressPolicyKey struct {
	SrcId     uint32
	DstId     uint32
	DstPort   uint16
	Proto     uint8
	Direction uint8
}

type TcEgressPolicyVerdict struct {
	Action uint8
	Flags  uint8
	Pad    uint16
}

// LoadTcEgress returns the embedded CollectionSpec for TcEgress.
func LoadTcEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcEgress: %w", err)
	}

	return spec, err
}

// LoadTcEgressObjects loads TcEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcEgressObjects
//	*TcEgressPrograms
//	*TcEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcEgressSpecs struct {
	TcEgressProgramSpecs
	TcEgressMapSpecs
	TcEgressVariableSpecs
}

// TcEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcEgressProgramSpecs struct {
	MeridianTcEgress *ebpf.ProgramSpec `ebpf:"meridian_tc_egress"`
}

// TcEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcEgressMapSpecs struct {
	DeniedFlowsMap    *ebpf.MapSpec `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.MapSpec `ebpf:"flow_events"`
	IdentityMap       *ebpf.MapSpec `ebpf:"identity_map"`
	MetricsMap        *ebpf.MapSpec `ebpf:"metrics_map"`
	PolicyMap         *ebpf.MapSpec `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.MapSpec `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.MapSpec `ebpf:"schema_sentinel_map"`
}

// TcEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcEgressVariableSpecs struct {
}

// TcEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcEgressObjects struct {
	TcEgressPrograms
	TcEgressMaps
	TcEgressVariables
}

func (o *TcEgressObjects) Close() error {
	return _TcEgressClose(
		&o.TcEgressPrograms,
		&o.TcEgressMaps,
	)
}

// TcEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcEgressMaps struct {
	DeniedFlowsMap    *ebpf.Map `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.Map `ebpf:"flow_events"`
	IdentityMap       *ebpf.Map `ebpf:"identity_map"`
	MetricsMap        *ebpf.Map `ebpf:"metrics_map"`
	PolicyMap         *ebpf.Map `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.Map `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.Map `ebpf:"schema_sentinel_map"`
}

func (m *TcEgressMaps) Close() error {
	return _TcEgressClose(
		m.DeniedFlowsMap,
		m.FlowEvents,
		m.IdentityMap,
		m.MetricsMap,
		m.PolicyMap,
		m.RuntimeConfigMap,
		m.SchemaSentinelMap,
	)
}

// TcEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcEgressVariables struct {
}

// TcEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcEgressPrograms struct {
	MeridianTcEgress *ebpf.Program `ebpf:"meridian_tc_egress"`
}

func (p *TcEgressPrograms) Close() error {
	return _TcEgressClose(
		p.MeridianTcEgress,
	)
}

func _TcEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcegress_bpfel.o
var _TcEgressBytes []byte
