// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type TcIngressDenyInfo struct {
	LastNs uint64
	Count  uint32
	Reason uint32
}

type TcIngressFlowEvent struct {
	TimestampNs  uint64
	SrcIp        uint32
	DstIp        uint32
	SrcPort      uint16
	DstPort      uint16
	Proto        uint8
	Verdict      uint8
	Pad0         uint16
	SrcIdentity  uint32
	DstIdentity  uint32
	Bytes        uint32
	Pad1         uint32
	LatencyNs    uint64
	L7StatusCode uint16
	Pad2         [3]uint16
}

type TcIngressFlowKey struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	Pad     [3]uint8
}

type TcIngressMeridianSchemaVersion uint32

const (
	TcIngressMeridianSchemaVersionMERIDIAN_SCHEMA_VERSION TcIngressMeridianSchemaVersion = 2
)

type TcIngressPolicyKey struct {
	SrcId     uint32
	DstId     uint32
	DstPort   uint16
	Proto     uint8
	Direction uint8
}

type TcIngressPolicyVerdict struct {
	Action uint8
	Flags  uint8
	Pad    uint16
}

type TcIngressSockKey struct {
	DstIp   uint32
	DstPort uint16
	Pad     uint16
}

// LoadTcIngress returns the embedded CollectionSpec for TcIngress.
func LoadTcIngress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcIngressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcIngress: %w", err)
	}

	return spec, err
}

// LoadTcIngressObjects loads TcIngress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcIngressObjects
//	*TcIngressPrograms
//	*TcIngressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcIngressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcIngress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcIngressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcIngressSpecs struct {
	TcIngressProgramSpecs
	TcIngressMapSpecs
	TcIngressVariableSpecs
}

// TcIngressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcIngressProgramSpecs struct {
	MeridianTcIngress *ebpf.ProgramSpec `ebpf:"meridian_tc_ingress"`
}

// TcIngressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcIngressMapSpecs struct {
	DeniedFlowsMap    *ebpf.MapSpec `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.MapSpec `ebpf:"flow_events"`
	IdentityMap       *ebpf.MapSpec `ebpf:"identity_map"`
	MetricsMap        *ebpf.MapSpec `ebpf:"metrics_map"`
	PolicyMap         *ebpf.MapSpec `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.MapSpec `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.MapSpec `ebpf:"schema_sentinel_map"`
	Sockhash          *ebpf.MapSpec `ebpf:"sockhash"`
	UdpSeenFlowsMap   *ebpf.MapSpec `ebpf:"udp_seen_flows_map"`
}

// TcIngressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcIngressVariableSpecs struct {
}

// TcIngressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcIngressObjects struct {
	TcIngressPrograms
	TcIngressMaps
	TcIngressVariables
}

func (o *TcIngressObjects) Close() error {
	return _TcIngressClose(
		&o.TcIngressPrograms,
		&o.TcIngressMaps,
	)
}

// TcIngressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcIngressMaps struct {
	DeniedFlowsMap    *ebpf.Map `ebpf:"denied_flows_map"`
	FlowEvents        *ebpf.Map `ebpf:"flow_events"`
	IdentityMap       *ebpf.Map `ebpf:"identity_map"`
	MetricsMap        *ebpf.Map `ebpf:"metrics_map"`
	PolicyMap         *ebpf.Map `ebpf:"policy_map"`
	RuntimeConfigMap  *ebpf.Map `ebpf:"runtime_config_map"`
	SchemaSentinelMap *ebpf.Map `ebpf:"schema_sentinel_map"`
	Sockhash          *ebpf.Map `ebpf:"sockhash"`
	UdpSeenFlowsMap   *ebpf.Map `ebpf:"udp_seen_flows_map"`
}

func (m *TcIngressMaps) Close() error {
	return _TcIngressClose(
		m.DeniedFlowsMap,
		m.FlowEvents,
		m.IdentityMap,
		m.MetricsMap,
		m.PolicyMap,
		m.RuntimeConfigMap,
		m.SchemaSentinelMap,
		m.Sockhash,
		m.UdpSeenFlowsMap,
	)
}

// TcIngressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcIngressVariables struct {
}

// TcIngressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcIngressPrograms struct {
	MeridianTcIngress *ebpf.Program `ebpf:"meridian_tc_ingress"`
}

func (p *TcIngressPrograms) Close() error {
	return _TcIngressClose(
		p.MeridianTcIngress,
	)
}

func _TcIngressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcingress_bpfel.o
var _TcIngressBytes []byte
