// Package telemetry consumes the kernel ring buffer of flow events and turns
// raw bpf2go-generated records into the agent's domain Event type.
//
// Wire vs domain types — read this before editing:
//
//   - bpf.CounterFlowEvent is the WIRE struct. Its layout is generated by
//     bpf2go from the C `struct flow_event` and must never be hand-edited; it
//     is the single source of truth for the on-ring byte layout.
//   - Event (below) is the DOMAIN type. It is hand-written on purpose: it is
//     NOT a wire struct. It holds decoded, normalised values (wall-clock time,
//     net.IP, host-order ports) for the aggregation layer and CLI. Changing
//     Event never changes the kernel/userspace ABI.
//
// This file is portable (no kernel, no cilium/ebpf) so the conversion and
// clock math are unit-testable anywhere; the reader lives in consumer_linux.go.
package telemetry

import (
	"net"
	"time"
)

// Verdict mirrors enum flow_verdict from meridian_types.h.
type Verdict uint8

const (
	VerdictAllow    Verdict = 0
	VerdictDeny     Verdict = 1
	VerdictRedirect Verdict = 2
)

// Event is the decoded, domain-level form of a kernel flow_event.
type Event struct {
	Timestamp    time.Time // wall-clock, boot-offset applied
	MonotonicNs  uint64    // raw bpf_ktime_get_ns, for ordering/debug
	SrcIP        net.IP
	DstIP        net.IP
	SrcPort      uint16
	DstPort      uint16
	Proto        uint8
	Verdict      Verdict
	SrcIdentity  uint32
	DstIdentity  uint32
	Bytes        uint32
	LatencyNs    uint64
	L7StatusCode uint16
}

// Handler receives one decoded Event per kernel record. It must not block for
// long: it runs on the reader goroutine. Downstream layers hand off to their
// own buffered structures.
type Handler func(Event)

// wallClock converts a raw CLOCK_MONOTONIC-since-boot timestamp to wall-clock
// time using a precomputed boot offset (CLOCK_REALTIME - CLOCK_MONOTONIC).
// Kernel timestamps are never compared to wall-clock directly. A zero
// monotonic value maps to the zero time ("no timestamp").
func wallClock(monotonicNs uint64, bootOffsetNs int64) time.Time {
	if monotonicNs == 0 {
		return time.Time{}
	}
	return time.Unix(0, int64(monotonicNs)+bootOffsetNs)
}

// ntohs converts a network-order uint16 (as stored verbatim in the kernel
// struct on a little-endian host) to host order.
func ntohs(netOrder uint16) uint16 {
	return (netOrder >> 8) | (netOrder << 8)
}

// ipFromBE32 reconstructs a net.IP from a uint32 that was loaded from kernel
// memory holding network-order bytes on a little-endian host: byte 0 of the
// address is the least-significant byte of the loaded value.
func ipFromBE32(be uint32) net.IP {
	return net.IPv4(byte(be), byte(be>>8), byte(be>>16), byte(be>>24)).To4()
}
